version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: deepseekers
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./  # Путь до директории, где лежит Dockerfile
      dockerfile: Dockerfile  # Имя Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/deepseekers
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./apps:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000

volumes:
  postgres_data:
